spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Karlshi45.
    driver-class-name: org.postgresql.Driver
server:
  port: 8888
cors:
  allowed-origins:
    - http://localhost:4200
  allowed-methods:
    - OPTIONS
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
  allowed-headers:
    - Accept
    - Authorization
    - Content-Type
    - Access-Control-Allow-Origins
    - Access-Control-Allow-Methods
    - Access-Control-Allow-Headers
  allow-credentials: true
---
spring:
  config:
    activate:
      on-profile:
        - prod
cors:
  allowed-origins:
    - http://revature-bank-runner.s3-website-us-east-1.amazonaws.com